### PR TITLE
Refactor and optimize codebase

### PR DESCRIPTION
**Pull request by RoachxD**
This pull request contains several changes to the codebase that aim to improve its readability and performance. The main changes are:

- Fixed `MD001/heading-increment/header-increment` rule violation in `README.md`.
- Fixed two vulnerabilities in `package-lock.json`.
- Combined multiple imports from the same module into a single import statement in `index.ts`.
- Removed unnecessary intermediate variables and replaced function declarations with arrow functions in `index.ts`, `context.ts`, `DateTime.tsx`, `I18nProvider.tsx`, `Number.tsx`, and `Text.tsx`.
- Moved some variables outside of the return statement to improve readability in `DateTime.tsx` and `Number.tsx`.
- Reversed the ternary operator in `DateTime.tsx` and `Number.tsx`.
- Changed the quotes used for the import statements from single to double.
- Added curly braces to the `if` statement in `context.ts`.

_Suggest using `Object.values` instead of `isEmpty` for micro-optimizing `DateTime.tsx` and `Number.tsx`._

These changes do not affect the functionality or the output of the code, but they make it more consistent, concise, and maintainable. I hope you find them useful and welcome any feedback or suggestions. Thank you for your time and consideration.

### CODE REVIEW

**Comment by SanichKotikov** [comment]
Hi. Thanks, but there are important rules for open source:

- Make a new issue (ask) before making any changes
- Don't change the exist formatting (tabs, quotes, etc.)

If you can get the formatting back, I can take a look and possibly accept this PR. Thanks any way.

**Comment by RoachxD** [comment]
Hello @SanichKotikov, will do! But first, I'd want to know if the aforementioned formatting include reverting back from `arrow functions` to `function` declarations?

**Comment by SanichKotikov** [comment]
@RoachxD It's preferable to use named functions, especially for components, because arrow functions can be marked as unknown/unnamed in some debug tools.

**Comment by RoachxD** [comment]
Do you think I should PR on [i18n-mini](https://github.com/SanichKotikov/i18n-mini) in regards to the optimized version of `isEmpty` instead of adding overhead to this?

**Comment by SanichKotikov** [comment]
@RoachxD thanks, but I can't merge this PR. I've asked you to reduce count of changes, but instead of this you add more and more... It's better to keep one thing in one PR.

**Comment by SanichKotikov** [comment]
@RoachxD I've made some updates. Thanks for highlighting some of the issues.

About Object.values and isEmpty, I think, it's better to update it in i18n-mini and keep functional style, for example use `some` insted of `every`.

**Comment by RoachxD** [comment]
@SanichKotikov I understand, sorry for being that unstructured because of my eagerness!

I will be creating multiple issues and wait for your answers in order to see if it's viable or not to create a PR based on your opinion. Thanks!

**Pull request closed without merging**
